apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktails-deployment
  namespace: cocktails
  labels:
    app: cocktails
spec:
  selector:
    matchLabels:
      app: cocktails
  replicas: 2
  template:
    metadata:
      labels:
        app: cocktails
    spec:
      containers:
      - name: cocktails
        image: kunalborkar2001/cocktail_adrian:latest
        ports:
        - containerPort: 5173
          
