 # https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cocktails
spec:
  selector:
    app: cocktails
  type: ClusterIP
  ports:
  - name: cocktails-port
    protocol: TCP
    port: 80
    targetPort: 5173
---
